builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
archives:
- format_overrides:
    - goos: windows
      format: zip
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
  prerelease: auto
dockers:
  - binaries:
    - "{{ .ProjectName }}"
    image_templates:
    - "docker.pkg.github.com/golang-templates/seed/{{ .ProjectName }}:latest"
    - "docker.pkg.github.com/golang-templates/seed/{{ .ProjectName }}:{{ .Major }}"
    - "docker.pkg.github.com/golang-templates/seed/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "docker.pkg.github.com/golang-templates/seed/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--build-arg=BINARY={{ .ProjectName }}"
