name: build

on:
  push:
    branches:
      - '*'

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.4
      - uses: actions/checkout@v2
      - name: Build
        run: make all
