name: release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Release
        run: make docker args="-e CI -e GITHUB_TOKEN" run="make all publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
